<?php

namespace App\Support;

class MarketData
{
    public static function categories(): array
    {
        return [
            ['id' => 'fashion', 'name' => 'Fashion', 'image' => '/assets/categories/card-fashion.png', 'href' => '/belanja?kategori=fashion', 'bgColor' => '#4F18C8'],
            ['id' => 'tas', 'name' => 'Tas & Aksesoris', 'image' => '/assets/categories/card-tas.png', 'href' => '/belanja?kategori=tas', 'bgColor' => '#F59E0B'],
            ['id' => 'hobi', 'name' => 'Hobi & Koleksi', 'image' => '/assets/categories/card-hobi.png', 'href' => '/belanja?kategori=hobi', 'bgColor' => '#4F18C8'],
            ['id' => 'merch', 'name' => 'Merchandise', 'image' => '/assets/categories/card-merch.png', 'href' => '/belanja?kategori=merchandise', 'bgColor' => '#F59E0B'],
            ['id' => 'elektronik', 'name' => 'Elektronik', 'image' => '/assets/categories/card-elektronik.png', 'href' => '/belanja?kategori=elektronik', 'bgColor' => '#4F18C8'],
            ['id' => 'kecantikan', 'name' => 'Kecantikan', 'image' => '/assets/categories/card-kecantikan.png', 'href' => '/belanja?kategori=kecantikan', 'bgColor' => '#F59E0B'],
        ];
    }

    public static function landingProducts(): array
    {
        return [
            [
                'id' => 'prod_1',
                'title' => 'Jaket Denim Vintage',
                'sellerName' => 'Raisy Febian',
                'sellerAvatar' => '/assets/avatars/avatar-raisy.png',
                'verified' => true,
                'condition' => 'Seperti Baru',
                'priceText' => 'Rp 450.000',
                'priceNumber' => 450000,
                'likes' => 124,
                'image' => '/assets/products/prod-denim.png',
                'href' => '#detail-denim',
            ],
            [
                'id' => 'prod_2',
                'title' => 'Hoodie Dream Plan Do',
                'sellerName' => 'Celloszx',
                'sellerAvatar' => '/assets/avatars/avatar-cellos.png',
                'verified' => true,
                'condition' => 'Sangat Baik',
                'priceText' => 'Rp 320.000',
                'priceNumber' => 320000,
                'likes' => 89,
                'image' => '/assets/products/prod-hoodie.png',
                'href' => '/produk/prod-hoodie-dream-plan-do',
            ],
            [
                'id' => 'prod_3',
                'title' => 'Totebag Limited Edition',
                'sellerName' => 'Windah Basudara',
                'sellerAvatar' => '/assets/avatars/avatar-windah.png',
                'verified' => true,
                'condition' => 'Baik',
                'priceText' => 'Rp 180.000',
                'priceNumber' => 180000,
                'likes' => 256,
                'image' => '/assets/products/prod-totebag.png',
                'href' => '#detail-totebag',
            ],
            [
                'id' => 'prod_4',
                'title' => 'Kartu Pokemon Rare',
                'sellerName' => 'MiawAug',
                'sellerAvatar' => '/assets/avatars/avatar-miawaug.png',
                'verified' => true,
                'condition' => 'Seperti Baru',
                'priceText' => 'Rp 1.500.000',
                'priceNumber' => 1500000,
                'likes' => 512,
                'image' => '/assets/products/prod-pokemon.png',
                'href' => '#detail-pokemon',
            ],
            [
                'id' => 'prod_5',
                'title' => 'Parfum Original Rare',
                'sellerName' => 'Anya Geraldine',
                'sellerAvatar' => '/assets/avatar-anya.png',
                'verified' => true,
                'condition' => 'Sangat Baik',
                'priceText' => 'Rp 650.000',
                'priceNumber' => 650000,
                'likes' => 80,
                'image' => '/assets/products/prod-parfum.png',
                'href' => '#detail-parfum',
            ],
        ];
    }

    public static function shopProducts(): array
    {
        return [
            [
                'id' => 'shop_1',
                'title' => 'Jaket Denim Vintage',
                'sellerName' => 'Raisy Febian',
                'sellerAvatar' => '/assets/avatars/avatar-raisy.png',
                'verified' => true,
                'priceText' => 'Rp 450.000',
                'priceNumber' => 450000,
                'likes' => 124,
                'image' => '/assets/products/prod-denim.png',
                'href' => '#detail-denim',
                'condition' => 'Seperti Baru',
                'category' => 'fashion',
                'location' => 'Jakarta Selatan',
            ],
            [
                'id' => 'shop_2',
                'title' => 'Hoodie Dream Plan Do',
                'sellerName' => 'Ceiloszx',
                'sellerAvatar' => '/assets/avatars/avatar-cellos.png',
                'verified' => true,
                'priceText' => 'Rp 320.000',
                'priceNumber' => 320000,
                'likes' => 89,
                'image' => '/assets/products/prod-hoodie.png',
                'href' => '/produk/prod-hoodie-dream-plan-do',
                'condition' => 'Sangat Baik',
                'category' => 'fashion',
                'location' => 'Jakarta Barat',
            ],
            [
                'id' => 'shop_3',
                'title' => 'Totebag Limited Edition',
                'sellerName' => 'Windah Basudara',
                'sellerAvatar' => '/assets/avatars/avatar-windah.png',
                'verified' => true,
                'priceText' => 'Rp 180.000',
                'priceNumber' => 180000,
                'likes' => 256,
                'image' => '/assets/products/prod-totebag.png',
                'href' => '#detail-totebag',
                'condition' => 'Seperti Baru',
                'category' => 'tas',
                'location' => 'Jakarta Timur',
            ],
            [
                'id' => 'shop_4',
                'title' => 'Kartu Pokemon Rare',
                'sellerName' => 'MiawAug',
                'sellerAvatar' => '/assets/avatars/avatar-miawaug.png',
                'verified' => true,
                'priceText' => 'Rp 1.500.000',
                'priceNumber' => 1500000,
                'likes' => 512,
                'image' => '/assets/products/prod-pokemon.png',
                'href' => '#detail-pokemon',
                'condition' => 'Seperti Baru',
                'category' => 'hobi',
                'location' => 'Jakarta Utara',
            ],
            [
                'id' => 'shop_5',
                'title' => 'Parfum Original Rare',
                'sellerName' => 'Anya Geraldine',
                'sellerAvatar' => '/assets/avatar-anya.png',
                'verified' => true,
                'priceText' => 'Rp 650.000',
                'priceNumber' => 650000,
                'likes' => 80,
                'image' => '/assets/products/prod-parfum.png',
                'href' => '#detail-parfum',
                'condition' => 'Sangat Baik',
                'category' => 'kecantikan',
                'location' => 'Jakarta Selatan',
            ],
            [
                'id' => 'shop_6',
                'title' => 'Nike Dunk Low Purple',
                'sellerName' => 'Jerome Polin',
                'sellerAvatar' => '/assets/avatar-jerome.png',
                'verified' => true,
                'priceText' => 'Rp 850.000',
                'priceNumber' => 850000,
                'likes' => 421,
                'image' => '/assets/products/prod-dunk.png',
                'href' => '#detail-dunk',
                'condition' => 'Baik',
                'category' => 'fashion',
                'location' => 'Surabaya',
            ],
            [
                'id' => 'shop_7',
                'title' => 'Tas Michael Kors',
                'sellerName' => 'Rachel Vennya',
                'sellerAvatar' => '/assets/avatar-rachel.png',
                'verified' => true,
                'priceText' => 'Rp 1.200.000',
                'priceNumber' => 1200000,
                'likes' => 310,
                'image' => '/assets/products/prod-bag.png',
                'href' => '#detail-bag',
                'condition' => 'Seperti Baru',
                'category' => 'tas',
                'location' => 'Jakarta Selatan',
            ],
            [
                'id' => 'shop_8',
                'title' => 'Instax Mini 11',
                'sellerName' => 'Fujii An',
                'sellerAvatar' => '/assets/avatars/avatar-fuji.png',
                'verified' => true,
                'priceText' => 'Rp 950.000',
                'priceNumber' => 950000,
                'likes' => 178,
                'image' => '/assets/products/prod-instax.png',
                'href' => '#detail-instax',
                'condition' => 'Sangat Baik',
                'category' => 'elektronik',
                'location' => 'Jakarta Barat',
            ],
            [
                'id' => 'shop_9',
                'title' => 'Hoodie Streamer Edition',
                'sellerName' => 'Verrell Bramasta',
                'sellerAvatar' => '/assets/avatars/avatar-verrell.png',
                'verified' => true,
                'priceText' => 'Rp 420.000',
                'priceNumber' => 420000,
                'likes' => 96,
                'image' => '/assets/products/prod-hoodie-black.png',
                'href' => '#detail-hoodie-black',
                'condition' => 'Seperti Baru',
                'category' => 'fashion',
                'location' => 'Jakarta Selatan',
            ],
            [
                'id' => 'shop_10',
                'title' => 'Bearbrick 400%',
                'sellerName' => 'Windah Basudara',
                'sellerAvatar' => '/assets/avatars/avatar-windah.png',
                'verified' => true,
                'priceText' => 'Rp 2.500.000',
                'priceNumber' => 2500000,
                'likes' => 320,
                'image' => '/assets/products/prod-bearbrick.png',
                'href' => '#detail-bearbrick',
                'condition' => 'Seperti Baru',
                'category' => 'hobi',
                'location' => 'Jakarta Timur',
            ],
            [
                'id' => 'shop_11',
                'title' => 'T-Shirt Official Tour',
                'sellerName' => 'Raisa Andriana',
                'sellerAvatar' => '/assets/avatars/avatar-raisa.png',
                'verified' => true,
                'priceText' => 'Rp 280.000',
                'priceNumber' => 280000,
                'likes' => 143,
                'image' => '/assets/products/prod-tshirt.png',
                'href' => '#detail-tshirt',
                'condition' => 'Baik',
                'category' => 'merchandise',
                'location' => 'Jakarta Selatan',
            ],
            [
                'id' => 'shop_12',
                'title' => 'Topi Whimarket',
                'sellerName' => 'MiawAug',
                'sellerAvatar' => '/assets/avatars/avatar-miawaug.png',
                'verified' => true,
                'priceText' => 'Rp 150.000',
                'priceNumber' => 150000,
                'likes' => 67,
                'image' => '/assets/products/prod-topi.png',
                'href' => '#detail-topi',
                'condition' => 'Seperti Baru',
                'category' => 'merchandise',
                'location' => 'Jakarta Utara',
            ],
            [
                'id' => 'shop_13',
                'title' => 'Buku Koleksi Pribadi',
                'sellerName' => 'Fujii An',
                'sellerAvatar' => '/assets/avatars/avatar-fuji.png',
                'verified' => true,
                'priceText' => 'Rp 120.000',
                'priceNumber' => 120000,
                'likes' => 91,
                'image' => '/assets/products/prod-buku.png',
                'href' => '#detail-buku',
                'condition' => 'Baik',
                'category' => 'hobi',
                'location' => 'Jakarta Barat',
            ],
            [
                'id' => 'shop_14',
                'title' => 'Gameboy Advance',
                'sellerName' => 'Jerome Polin',
                'sellerAvatar' => '/assets/avatar-jerome.png',
                'verified' => true,
                'priceText' => 'Rp 780.000',
                'priceNumber' => 780000,
                'likes' => 204,
                'image' => '/assets/products/prod-gameboy.png',
                'href' => '#detail-gameboy',
                'condition' => 'Seperti Baru',
                'category' => 'elektronik',
                'location' => 'Surabaya',
            ],
            [
                'id' => 'shop_15',
                'title' => 'Jaket Varsity',
                'sellerName' => 'Anya Geraldine',
                'sellerAvatar' => '/assets/avatar-anya.png',
                'verified' => true,
                'priceText' => 'Rp 520.000',
                'priceNumber' => 520000,
                'likes' => 118,
                'image' => '/assets/products/prod-varsity.png',
                'href' => '#detail-varsity',
                'condition' => 'Sangat Baik',
                'category' => 'fashion',
                'location' => 'Jakarta Selatan',
            ],
        ];
    }

    public static function sellers(): array
    {
        return [
            ['id' => 'sel_1', 'name' => 'Raisa Andriana', 'handle' => '@raisa6690', 'role' => 'Artis', 'avatar' => '/assets/avatars/avatar-raisa.png', 'verified' => true, 'rating' => 4.9, 'itemCount' => 128, 'salesCount' => 120],
            ['id' => 'sel_2', 'name' => 'Verrell Bramasta', 'handle' => '@bramastavrl', 'role' => 'Aktor', 'avatar' => '/assets/avatars/avatar-verrell.png', 'verified' => true, 'rating' => 4.8, 'itemCount' => 96, 'salesCount' => 85],
            ['id' => 'sel_3', 'name' => 'Fuji An', 'handle' => '@fuji_an', 'role' => 'Kreator', 'avatar' => '/assets/avatars/avatar-fuji.png', 'verified' => true, 'rating' => 4.9, 'itemCount' => 142, 'salesCount' => 180],
            ['id' => 'sel_4', 'name' => 'Windah Basudara', 'handle' => '@windahbasudara', 'role' => 'Streamer', 'avatar' => '/assets/avatars/avatar-windah.png', 'verified' => true, 'rating' => 5.0, 'itemCount' => 210, 'salesCount' => 290],
            ['id' => 'sel_5', 'name' => 'Rachel Vennya', 'handle' => '@rachelvennya', 'role' => 'Kreator', 'avatar' => '/assets/avatar-rachel.png', 'verified' => true, 'rating' => 4.9, 'itemCount' => 115, 'salesCount' => 120],
        ];
    }

    public static function steps(): array
    {
        return [
            ['stepNumber' => 1, 'title' => 'Temukan Barang Favorit', 'description' => 'Jelajahi barang dari figur publik favoritmu.', 'image' => '/assets/steps/step-1-clean.png'],
            ['stepNumber' => 2, 'title' => 'Transaksi Aman', 'description' => 'Lakukan pembayaran dengan sistem escrow Whimarket.', 'image' => '/assets/steps/step-2-clean.png'],
            ['stepNumber' => 3, 'title' => 'Barang Dikirim', 'description' => 'Penjual mengirim barang setelah pembayaran terverifikasi.', 'image' => '/assets/steps/step-3-truck.png'],
            ['stepNumber' => 4, 'title' => 'Barang Diterima', 'description' => 'Barang sampai di tanganmu dengan aman!', 'image' => '/assets/steps/step-4-clean.png'],
        ];
    }

    public static function productDetail(): array
    {
        return [
            'id' => 'prod-hoodie-dream-plan-do',
            'title' => 'Hoodie Dream Plan Do – Purple',
            'category' => 'Fashion',
            'category_slug' => 'fashion',
            'subcategory' => 'Hoodie',
            'badge' => 'Official Merchandise',
            'price' => 500000,
            'price_formatted' => 'Rp 500.000',
            'rating' => 4.8,
            'review_count' => 620,
            'sold_count' => '900+',
            'description' => 'Hoodie eksklusif dari Celloszx dengan desain "Dream Plan Do". Nyaman dipakai, cocok untuk aktivitas sehari-hari maupun koleksi.',
            'stock' => 120,
            'seller' => [
                'name' => 'Celloszx',
                'username' => 'celloszx',
                'role' => 'Content Creator',
                'avatar' => '/assets/detail/celloszx_avatar.png',
                'verified' => true,
                'href' => '/seller/@celloszx',
            ],
            'breadcrumbs' => [
                ['name' => 'Beranda', 'href' => '/'],
                ['name' => 'Fashion', 'href' => '/belanja?kategori=fashion'],
                ['name' => 'Hoodie', 'href' => '/belanja?kategori=fashion'],
                ['name' => 'Hoodie Dream Plan Do – Purple', 'href' => null],
            ],
            'gallery' => [
                ['id' => 'front', 'thumb' => '/assets/products/prod-hoodie.png', 'main' => '/assets/products/prod-hoodie.png', 'alt' => 'Hoodie Dream Plan Do - Depan'],
                ['id' => 'model', 'thumb' => '/assets/detail/hoodie_model.png', 'main' => '/assets/detail/hoodie_model.png', 'alt' => 'Model Memakai Hoodie Dream Plan Do'],
                ['id' => 'back', 'thumb' => '/assets/detail/hoodie_back.png', 'main' => '/assets/detail/hoodie_back.png', 'alt' => 'Hoodie Dream Plan Do - Belakang'],
                ['id' => 'text', 'thumb' => '/assets/detail/hoodie_text_detail.png', 'main' => '/assets/detail/hoodie_text_detail.png', 'alt' => 'Detail Desain Dream Plan Do'],
                ['id' => 'tag', 'thumb' => '/assets/detail/hoodie_tag_detail.png', 'main' => '/assets/detail/hoodie_tag_detail.png', 'alt' => 'Detail Kerah & Tag Hoodie'],
            ],
            'colors' => [
                ['id' => 'purple', 'name' => 'Purple', 'image' => '/assets/products/prod-hoodie.png', 'active' => true],
                ['id' => 'black', 'name' => 'Black', 'image' => '/assets/detail/hoodie_color_black.png', 'active' => false],
                ['id' => 'white', 'name' => 'White', 'image' => '/assets/detail/hoodie_color_white.png', 'active' => false],
                ['id' => 'grey', 'name' => 'Grey', 'image' => '/assets/detail/hoodie_color_grey.png', 'active' => false],
            ],
            'sizes' => ['S', 'M', 'L', 'XL', 'XXL'],
            'default_size' => 'L',
            'features' => [
                ['title' => 'Produk Original', 'desc' => 'Dari seller terpercaya', 'icon' => 'shield-check'],
                ['title' => 'Pengiriman Cepat', 'desc' => 'Diproses maks. 1×24 jam', 'icon' => 'truck'],
                ['title' => 'Bisa Retur', 'desc' => 'Sesuai kebijakan Whimarket', 'icon' => 'refresh'],
                ['title' => 'Pembayaran Aman', 'desc' => 'Dengan escrow Whimarket', 'icon' => 'shield-lock'],
            ],
            'trust_badges' => [
                ['title' => 'Original & Terverifikasi', 'desc' => 'Produk 100% asli', 'icon' => 'verified'],
                ['title' => 'Dari Kreator Favoritmu', 'desc' => 'Langsung dari kreator pilihan', 'icon' => 'user'],
                ['title' => 'Pengiriman Cepat', 'desc' => 'Diproses dalam 1×24 jam', 'icon' => 'truck'],
                ['title' => 'Transaksi Aman', 'desc' => 'Dengan sistem escrow', 'icon' => 'lock'],
            ],
            'rating_summary' => [
                'rating' => 4.8,
                'total_reviews' => 620,
                'breakdown' => [
                    ['star' => 5, 'count' => '528', 'pct' => 85],
                    ['star' => 4, 'count' => '68', 'pct' => 11],
                    ['star' => 3, 'count' => '16', 'pct' => 2.5],
                    ['star' => 2, 'count' => '5', 'pct' => 1],
                    ['star' => 1, 'count' => '3', 'pct' => 0.5],
                ],
            ],
            'reviews' => [
                [
                    'id' => 1,
                    'user_name' => 'Fuji An',
                    'user_avatar' => '/assets/avatars/avatar-fuji.png',
                    'rating' => 5,
                    'date' => '2 hari lalu',
                    'comment' => 'Bahan hoodie-nya tebel dan adem banget! Warna purple-nya cakep pol, sesuai foto. Pengiriman dari Celloszx cepet dan packing aman.',
                    'photos' => [
                        '/assets/review-hoodie-1.png',
                        '/assets/review-hoodie-2.png',
                    ],
                    'likes' => 24,
                ],
                [
                    'id' => 2,
                    'user_name' => 'Jerome Polin',
                    'user_avatar' => '/assets/avatar-jerome.png',
                    'rating' => 5,
                    'date' => '5 hari lalu',
                    'comment' => 'Mantappu Jiwa! Ukuran L-nya pas banget di badan, sablon bordir Dream Plan Do-nya rapi parah. Recommended merchandise!',
                    'photos' => [
                        '/assets/review-hoodie-3.png',
                    ],
                    'likes' => 42,
                ],
                [
                    'id' => 3,
                    'user_name' => 'Anya Geraldine',
                    'user_avatar' => '/assets/avatar-anya.png',
                    'rating' => 5,
                    'date' => '1 minggu lalu',
                    'comment' => 'Suka banget sama bahannya yang lembut di kulit, gak bikin gerah. Worth it buat koleksi!',
                    'photos' => [],
                    'likes' => 15,
                ],
            ],
        ];
    }
}
